- name: Playbook to Import VM on to AWS.
  hosts: localhost

  vars_files:
  - /home/controller/ansible_playbooks/ansible_aws_migration/external_vars.yml

  tasks:

    - name: Create an S3 bucket to upload the exported OVA.
      amazon.aws.s3_bucket:
        name: "{{ aws_bucket_name }}"
        state: present
        encryption: aws:kms
      tags:
      - bucket_create


    - name: Upload an object to the  bucket
      aws_s3:
        bucket: "{{ aws_bucket_name }}"
        object: "{{ ObjectDestination }}"
        src: "{{ ObjectSource }}"
        mode: put
        overwrite: never
      tags:
        - bucket_upload
   

    - name: Create IAM user with API Keys.
      community.aws.iam:
        iam_type: user
        name: sachin
        state: present
        password: "{{ temp_pass }}"
        trust_policy_filepath: trust-policy.json
        access_key_state: create

    - name: Create IAM role
      community.aws.iam:
        iam_type: role
        name: vmimport
        state: present
        trust_policy:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service: vmie.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:Externalid: vmimport

    - name: Attach inline IAM policy for the role 
      community.aws.iam_policy: 
        iam_type: role
        iam_name: vmimport
        state: present
        policy_name: vmimport
        policy_json: " {{ lookup( 'file', 'role_policy.json') }} "
        
    - name: Use the following command to import an image with a single disk.
      shell: |
        aws ec2 import-image --description "MyserverVM" --disk-containers "file://containers.json" --tag-specifications ResourceType=import-image-task,Tags="{Key=name,Value=ansible_ami}"
      register: result
      tags:
          - import_ami

    - name: Describing the import-image command
      shell: | 
        aws ec2 describe-import-image-tasks --import-task-ids import-ami-050a0c6d0f9026ac2
      register: output
      tags:
        - import_describe
    
    - name: Imported AMI Details
      ansible.builtin.debug:
         msg: The ImportTaskId of the imported image is{{ output.stdout_lines[3].split(':')[1] }}. Please use the given command to verify the progress of import - aws ec2 describe-import-image-tasks --import-task-ids {{ output.stdout_lines[3].split(':')[1] }}
      tags:
        - debug_ami_output
    
